[surfpool]
# Basic surfpool configuration
name = "block-markets-surfpool"
version = "1.0.0"

# Network configuration
[network]
# This will be overridden by command line --rpc-url flag
rpc_url = "https://api.mainnet-beta.solana.com"

# Deployment configuration
[deployment]
# Add any specific deployment configurations here as needed
