[alias]
surfpool-install = "install --path crates/cli --locked --force --features supervisor_ui --features version_check"
surfpool-install-dev = "install --path crates/cli --locked --force --features supervisor_ui"
