import type { Address } from '@solana/kit';

// ── Auto-generated param/response types (from ts-rs) ───────────────────────
// These are generated by `cargo test --features ts` from crates/types and crates/core.
// Do not edit the files in ./generated/ — regenerate with `bun run generate`.

export type { AccountSnapshot } from './generated/AccountSnapshot.ts';
export type { AccountUpdate } from './generated/AccountUpdate.ts';
export type { CheatcodeControlConfig } from './generated/CheatcodeControlConfig.ts';
export type { CheatcodeFilter } from './generated/CheatcodeFilter.ts';
export type { ComputeUnitsEstimationResult } from './generated/ComputeUnitsEstimationResult.ts';
export type { ExportSnapshotConfig } from './generated/ExportSnapshotConfig.ts';
export type { ExportSnapshotFilter } from './generated/ExportSnapshotFilter.ts';
export type { ExportSnapshotScope } from './generated/ExportSnapshotScope.ts';
export type { GetStreamedAccountsResponse } from './generated/GetStreamedAccountsResponse.ts';
export type { GetSurfnetInfoResponse } from './generated/GetSurfnetInfoResponse.ts';
export type { OfflineAccountConfig } from './generated/OfflineAccountConfig.ts';
export type { ResetAccountConfig } from './generated/ResetAccountConfig.ts';
export type { RpcProfileDepth } from './generated/RpcProfileDepth.ts';
export type { RpcProfileResultConfig } from './generated/RpcProfileResultConfig.ts';
export type { RunbookExecutionStatusReport } from './generated/RunbookExecutionStatusReport.ts';
export type { SetSomeAccount } from './generated/SetSomeAccount.ts';
export type { StreamAccountConfig } from './generated/StreamAccountConfig.ts';
export type { StreamedAccountInfo } from './generated/StreamedAccountInfo.ts';
export type { SupplyUpdate } from './generated/SupplyUpdate.ts';
export type { TimeTravelConfig } from './generated/TimeTravelConfig.ts';
export type { TokenAccountUpdate } from './generated/TokenAccountUpdate.ts';
export type { UiAccountChange } from './generated/UiAccountChange.ts';
export type { UiAccountProfileState } from './generated/UiAccountProfileState.ts';
export type { UiKeyedProfileResult } from './generated/UiKeyedProfileResult.ts';
export type { UiProfileResult } from './generated/UiProfileResult.ts';
export type { UuidOrSignature } from './generated/UuidOrSignature.ts';

// ── Import generated types used in API definitions below ────────────────────

import type { AccountUpdate } from './generated/AccountUpdate.ts';
import type { ExportSnapshotConfig } from './generated/ExportSnapshotConfig.ts';
import type { GetStreamedAccountsResponse } from './generated/GetStreamedAccountsResponse.ts';
import type { GetSurfnetInfoResponse } from './generated/GetSurfnetInfoResponse.ts';
import type { ResetAccountConfig } from './generated/ResetAccountConfig.ts';
import type { RpcProfileResultConfig } from './generated/RpcProfileResultConfig.ts';
import type { StreamAccountConfig } from './generated/StreamAccountConfig.ts';
import type { SupplyUpdate } from './generated/SupplyUpdate.ts';
import type { TimeTravelConfig } from './generated/TimeTravelConfig.ts';
import type { TokenAccountUpdate } from './generated/TokenAccountUpdate.ts';
import type { UiKeyedProfileResult } from './generated/UiKeyedProfileResult.ts';
import type { AccountSnapshot } from './generated/AccountSnapshot.ts';

// ── RPC-only types (not in Rust source) ─────────────────────────────────────

/** Clock state returned by timeTravel, pauseClock, resumeClock. Matches EpochInfo. */
export type ClockState = Readonly<{
    absoluteSlot: number;
    blockHeight: number;
    epoch: number;
    slotIndex: number;
    slotsInEpoch: number;
    transactionCount: number;
}>;

/** Anchor IDL structure for registerIdl / getActiveIdl. */
export type AnchorIdl = Readonly<{
    address: Address;
    accounts?: readonly unknown[];
    constants?: readonly unknown[];
    errors?: readonly unknown[];
    events?: readonly unknown[];
    instructions: readonly unknown[];
    metadata: Readonly<{
        name: string;
        version: string;
        spec: string;
        description?: string;
    }>;
    state?: unknown;
    types?: readonly unknown[];
}>;

/** Scenario for registerScenario. */
export type ScenarioOverride = Readonly<{
    id: string;
    templateId: string;
    values: Record<string, unknown>;
    scenarioRelativeSlot: number;
    label: string;
    enabled: boolean;
    fetchBeforeUse: boolean;
    account: Readonly<{ pubkey: Address }>;
}>;

export type Scenario = Readonly<{
    id: string;
    name: string;
    description: string;
    overrides: readonly ScenarioOverride[];
    tags: readonly string[];
}>;

/** Entry returned by getLocalSignatures. */
export type LocalSignatureEntry = Readonly<{
    signature: string;
    logs: readonly string[];
    err: Readonly<{ errorType: string; message: string }> | null;
}>;

/** Profiling result returned by profileTransaction. */
export type ComputeUnitsProfile = Readonly<{
    computeUnitsConsumed: number;
    errorMessage: string | null;
    logMessages: readonly string[];
    success: boolean;
}>;

export type TransactionProfileResult = Readonly<{
    computeUnits: ComputeUnitsProfile;
    state: Readonly<{
        preExecution: unknown;
        postExecution: unknown;
    }>;
}>;

// ── Per-method API types ────────────────────────────────────────────────────

// Clock
export type SurfnetTimeTravelApi = {
    timeTravel(config: TimeTravelConfig): ClockState;
};
export type SurfnetPauseClockApi = {
    pauseClock(): ClockState;
};
export type SurfnetResumeClockApi = {
    resumeClock(): ClockState;
};

// Accounts
export type SurfnetSetAccountApi = {
    setAccount(pubkey: Address, update: AccountUpdate): null;
};
export type SurfnetSetTokenAccountApi = {
    setTokenAccount(
        owner: Address,
        mint: Address,
        update: TokenAccountUpdate,
        tokenProgram?: Address,
    ): null;
};
export type SurfnetResetAccountApi = {
    resetAccount(pubkey: Address, config?: ResetAccountConfig): null;
};
export type SurfnetStreamAccountApi = {
    streamAccount(pubkey: Address, config?: StreamAccountConfig): null;
};
export type SurfnetGetStreamedAccountsApi = {
    getStreamedAccounts(): GetStreamedAccountsResponse;
};

// Programs
export type SurfnetCloneProgramAccountApi = {
    cloneProgramAccount(sourceProgramId: Address, destinationProgramId: Address): null;
};
export type SurfnetSetProgramAuthorityApi = {
    setProgramAuthority(programId: Address, newAuthority?: Address): null;
};
export type SurfnetWriteProgramApi = {
    writeProgram(
        programId: Address,
        data: string,
        offset: number,
        authority?: Address,
    ): null;
};

// Profiling
export type SurfnetProfileTransactionApi = {
    profileTransaction(
        transactionData: string,
        tag?: string,
        config?: RpcProfileResultConfig,
    ): TransactionProfileResult;
};
export type SurfnetGetTransactionProfileApi = {
    getTransactionProfile(
        signatureOrUuid: string,
        config?: RpcProfileResultConfig,
    ): UiKeyedProfileResult;
};
export type SurfnetGetProfileResultsByTagApi = {
    getProfileResultsByTag(
        tag: string,
        config?: RpcProfileResultConfig,
    ): readonly TransactionProfileResult[];
};

// IDL
export type SurfnetRegisterIdlApi = {
    registerIdl(idl: AnchorIdl, slot?: number): null;
};
export type SurfnetGetActiveIdlApi = {
    getActiveIdl(programId: Address, slot?: number): AnchorIdl | null;
};

// Network
export type SurfnetSetSupplyApi = {
    setSupply(update: SupplyUpdate): null;
};
export type SurfnetResetNetworkApi = {
    resetNetwork(): null;
};
export type SurfnetGetSurfnetInfoApi = {
    getSurfnetInfo(): GetSurfnetInfoResponse;
};
export type SurfnetExportSnapshotApi = {
    exportSnapshot(config?: ExportSnapshotConfig): Record<string, AccountSnapshot>;
};

// Scenario
export type SurfnetRegisterScenarioApi = {
    registerScenario(scenario: Scenario, slot?: number): null;
};

// Local
export type SurfnetGetLocalSignaturesApi = {
    getLocalSignatures(limit?: number): readonly LocalSignatureEntry[];
};

// ── Composed API ────────────────────────────────────────────────────────────

export type SurfnetCheatcodesApi = SurfnetTimeTravelApi &
    SurfnetPauseClockApi &
    SurfnetResumeClockApi &
    SurfnetSetAccountApi &
    SurfnetSetTokenAccountApi &
    SurfnetResetAccountApi &
    SurfnetStreamAccountApi &
    SurfnetGetStreamedAccountsApi &
    SurfnetCloneProgramAccountApi &
    SurfnetSetProgramAuthorityApi &
    SurfnetWriteProgramApi &
    SurfnetProfileTransactionApi &
    SurfnetGetTransactionProfileApi &
    SurfnetGetProfileResultsByTagApi &
    SurfnetRegisterIdlApi &
    SurfnetGetActiveIdlApi &
    SurfnetSetSupplyApi &
    SurfnetResetNetworkApi &
    SurfnetGetSurfnetInfoApi &
    SurfnetExportSnapshotApi &
    SurfnetRegisterScenarioApi &
    SurfnetGetLocalSignaturesApi;
