name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_cargo_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - uses: actions/checkout@v4
      - name: Rust install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Rustup install clippy
        run: rustup component add clippy
      - name: Run Cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: Run Cargo clippy
        run: cargo clippy --all-targets
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --features geyser-plugin
      - name: Run tests
        run: cargo test --all --verbose --features "ignore_tests_ci geyser-plugin"
